version: '3'
services:
    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - 2181:2181
    kafka:
        image: confluentinc/cp-kafka:latest
        depends_on:
            - zookeeper
        ports:
            - 9092:9092
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    kafdrop:
        image: obsidiandynamics/kafdrop
        network_mode: host
        depends_on:
            - kafka
        environment:
            KAFKA_BROKERCONNECT: localhost:9092
            JVM_OPTS: -Xms32M -Xmx64M
            SERVER_SERVLET_CONTEXTPATH: /
    elasticsearch:
        image: elasticsearch:7.14.0
        ports:
            - 9200:9200
            - 9300:9300
        environment:
            discovery.type: single-node
            ES_JAVA_OPTS: -Xms512m -Xmx512m
        ulimits:
            memlock:
                soft: -1
                hard: -1
    kibana:
        image: kibana:7.14.0
        network_mode: host
        depends_on:
            - elasticsearch
        environment:
            ELASTICSEARCH_HOSTS: '["http://localhost:9200"]'
